services:
  frontend:
    image: nginx:latest
    container_name: tracks_frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: tracks_redis
    restart: always
    command: [
      "redis-server",
      "--save", "",             # no RDB snapshots (sessions are ephemeral)
      "--appendonly", "no",     # disable AOF for sessions
      "--requirepass", "${REDIS_PASSWORD}",
      "--maxmemory", "256mb",   # cap memory
      "--maxmemory-policy", "volatile-ttl"  # evict expiring keys first
    ]
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app_network

  api:
    build: ./backend
    container_name: tracks_api
    restart: always
    environment:
      - NODE_ENV=production
      - CERT_DIR=/app/certs
    env_file:
      - ./backend/.env.production
    depends_on:
      - mongo
      - minio
      - redis
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./backend/certs:/app/certs:ro

  mongo:
    image: mongo:6
    container_name: tracks_db
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=tracks
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: tracks_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"  # API access
      - "9001:9001"  # Web console
    volumes:
      - minio_data:/data
    networks:
      - app_network

volumes:
  mongo_data:
  minio_data:

networks:
  app_network:
    driver: bridge